# AUTOGARD : 자동미분
#### autogard 패키지는 tensor의 모든 연산에 대해 자동 미분을 제공.
    
    tensor A 의 requires_gard 속성을 True로 설정한다면,
    A에서 이뤄진 모든 연산들을 추적한다.
    계산이 완료 후 .backward()를 호출하면 gradient를 자동으로 계산 할 수 있다.
    default 는 false 이다.
    
    .requires_grad_(True or False) 하면 
    기존의 만들어진 tensor의 requires_grad 값을 변경 할 수 있다.
    
    .detach()를 호출하면 연산 추적을 멈출 수 있다.
    with torch.no_grad():로 감싸주면 해당 블럭 안에서는 기록 추적을 하지 않는다.
    
    tensor들은 .grad_fn() 속성을 가지고 있는데,
    이것은 tensor를 생성한 function을 참조한다.
    (function이라고 적었지만, 연산이 될 수도 있음)
    어떠한 연산으로 tensor가 만들어졌는지를 표시해준다.
    단, 사용자가 만든 tensor는 예외이고, 이 때 grad_fn = none 이다.

In [32]:
import torch

In [33]:
w =  torch.tensor(2.0, requires_grad=True)

y= w ** 2

z = 2*y + 5

z.backward()
# z' = 2 * w^2 = 8

print("w 미분 값 : {}".format(w.grad))

w 미분 값 : 8.0


In [38]:
y = torch.tensor([[2.0, 2.0], [2.0, 2.0]], requires_grad=True)

z = y * y * y * 2

out = z.mean()
print(z)
print(z.grad_fn)
print(out)
print(out.grad_fn)

tensor([[16., 16.],
        [16., 16.]], grad_fn=<MulBackward0>)
tensor(16., grad_fn=<MeanBackward0>)


In [39]:
# 마지막 연산의 output인 out.backward를 하면 관련 연산이 모두 미분됨
out.backward()

# y에 대한 미분값 도출
# out = z.mean(), z = y^3 * 2  ==> z` = 3y 
print(y.grad)

tensor([[6., 6.],
        [6., 6.]])


In [58]:
x = torch.randn(2, requires_grad=True)
print(x)


print((x ** 2 * 2).requires_grad)

with torch.no_grad():
    print((x ** 2 * 2).requires_grad)

tensor([0.4506, 0.6085], requires_grad=True)
True
False


In [61]:
print(x.requires_grad)
y = x. detach()
print(y.requires_grad)
print(x.eq(y).all())
# x, y를 비교해서 같은 값을 출력. .all()이므로 전체 부분이 같으면 true 출력

True
False
tensor(True)
