In [11]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim


class LinearRegressionModel(nn.Module) :
    def __init__(self):
        super().__init__()
        # 단순 선형회귀이므로 입,출력이 1차원.
        self.linear = nn.Linear(1,1)
        
    # x는 input data가 된다. ex) y = model(x)
    def forward(self, x):
        return self.linear(x)
    
    
    
model = LinearRegressionModel()


위의 LinearRegressionModel은 

model = nn.Linear(1,1)과 같다.

위와 같은 구현 방식은 대부분의 파이토치 구현체에서 사용하는 방식이다.

숙지하면 좋다.

### 코드 설명
    nn.Module을 상속받는다. 
    super() 함수를 부르면 LinearRegressionModel 클래스는 nn.module의 속성을 가지고 초기화된다.
    
   #### forward()함수
       모델이 학습데이터를 받으면 forward 연산을 실행시키는 부분.
       forward()함수는 model객체를 데이터와 함께 호출하면 자동으로 실행됨.
       ex) output = model(input) ==> model안의 forward()함수가 자동으로 호출되서 실행됨.

In [12]:
class MultivariateLinearRegressionModel(nn.Module) :
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3,1)
        
    def forward(self, x):
        return self.linear(x)
    
model = MultivariateLinearRegressionModel()
print(model)


MultivariateLinearRegressionModel(
  (linear): Linear(in_features=3, out_features=1, bias=True)
)


### 단순 선형 회귀 클래스로 구현

In [13]:
torch.manual_seed(1)

x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [14]:
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1,1)
        
    def forward(self, x) :
        return self.linear(x)
    
model = LinearRegressionModel()

In [15]:
optimizer = optim.SGD(model.parameters(), lr=1e-2)

epochs = 2000

for e in range(epochs + 1) :
    pred = model(x_train)
    
    cost = F.mse_loss(pred, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if e % 100 == 0 :
        print("Epoch : {}/{} Cost : {:.6f}".format(e, epochs, cost.item()))

Epoch : 0/2000 Cost : 13.103541
Epoch : 100/2000 Cost : 0.002791
Epoch : 200/2000 Cost : 0.001724
Epoch : 300/2000 Cost : 0.001066
Epoch : 400/2000 Cost : 0.000658
Epoch : 500/2000 Cost : 0.000407
Epoch : 600/2000 Cost : 0.000251
Epoch : 700/2000 Cost : 0.000155
Epoch : 800/2000 Cost : 0.000096
Epoch : 900/2000 Cost : 0.000059
Epoch : 1000/2000 Cost : 0.000037
Epoch : 1100/2000 Cost : 0.000023
Epoch : 1200/2000 Cost : 0.000014
Epoch : 1300/2000 Cost : 0.000009
Epoch : 1400/2000 Cost : 0.000005
Epoch : 1500/2000 Cost : 0.000003
Epoch : 1600/2000 Cost : 0.000002
Epoch : 1700/2000 Cost : 0.000001
Epoch : 1800/2000 Cost : 0.000001
Epoch : 1900/2000 Cost : 0.000000
Epoch : 2000/2000 Cost : 0.000000


In [16]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


Weight = 2, bias = 0 으로 최적화된 것을 볼 수 있다.

### 다중 선형 회귀 클래스로 구현

In [22]:
torch.manual_seed(1)

x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [30]:
class MultivariateLinearRegressionModel(nn.Module) :
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1)
        
    def forward(self, x):
        return self.linear(x)
    
model = MultivariateLinearRegressionModel()

In [31]:
optimizer = optim.SGD(model.parameters(), lr=1e-5)

epochs = 2000

for e in range(epochs + 1):
    
    pred = model(x_train)
    
    cost = F.mse_loss(pred, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if e % 100 == 0 :
        print("Epoch : {}/{} Cost : {:.10f}".format(e, epochs, cost.item()))

Epoch : 0/2000 Cost : 24821.3710937500
Epoch : 100/2000 Cost : 0.8491477966
Epoch : 200/2000 Cost : 0.8255969882
Epoch : 300/2000 Cost : 0.8032250404
Epoch : 400/2000 Cost : 0.7819682360
Epoch : 500/2000 Cost : 0.7617790103
Epoch : 600/2000 Cost : 0.7425867319
Epoch : 700/2000 Cost : 0.7243570685
Epoch : 800/2000 Cost : 0.7070248723
Epoch : 900/2000 Cost : 0.6905483007
Epoch : 1000/2000 Cost : 0.6748827696
Epoch : 1100/2000 Cost : 0.6599851847
Epoch : 1200/2000 Cost : 0.6458097696
Epoch : 1300/2000 Cost : 0.6323423386
Epoch : 1400/2000 Cost : 0.6195142269
Epoch : 1500/2000 Cost : 0.6073073745
Epoch : 1600/2000 Cost : 0.5956887007
Epoch : 1700/2000 Cost : 0.5846163630
Epoch : 1800/2000 Cost : 0.5740810037
Epoch : 1900/2000 Cost : 0.5640445948
Epoch : 2000/2000 Cost : 0.5544735789


In [32]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.7497, 0.4868, 0.7725]], requires_grad=True), Parameter containing:
tensor([0.0386], requires_grad=True)]
